### ISSUE TITLE
forms_bot not working with latest rasa_core release

### ISSUE THREAD

**Issue by oldmonkABA** [RasaHQ/forms_bot#4]
I am getting the  following error when i am trying to run the forms_bot code

Bot loaded. Type a message and press enter (use '/stop' to exit): 
hi
2018-10-01 17:56:09 DEBUG    requests.packages.urllib3.connectionpool  - Starting new HTTP connection (1): localhost
2018-10-01 17:56:09 DEBUG    rasa_core.tracker_store  - Creating a new tracker for id 'default'.
2018-10-01 17:56:09 DEBUG    rasa_core.processor  - Received user message 'hi' with intent '{'name': 'hi', 'confidence': 1.0}' and entities '[]'
2018-10-01 17:56:09 DEBUG    rasa_core.processor  - Logged UserUtterance - tracker now has 2 events
2018-10-01 17:56:09 DEBUG    rasa_core.processor  - Current slot values: 
        people: None
        has_gym: None
        breakfast: None
        requested_slot: None
        location: None
        info: None
        outdoor_seating: None
        hotel: None
        enddate: None
        restaurant: None
        cuisine: None
        plan_complete: None
        price: None
        reservations: None
        startdate: None
        date_suitable: None
        has_spa: None
2018-10-01 17:56:09 DEBUG    rasa_core.policies.memoization  - Current tracker state [None, {}, {'prev_action_listen': 1.0, 'intent_hi': 1.0}]
2018-10-01 17:56:09 DEBUG    rasa_core.policies.memoization  - There is no memorised next action
2018-10-01 17:56:09 DEBUG    rasa_core.featurizers  - Feature 'intent_hi' (value: '1.0') could not be found in feature map. Make sure you added all intents and entities to the domain
2018-10-01 17:56:09 DEBUG    rasa_core.policies.ensemble  - Predicted next action using policy_2_KerasPolicy
2018-10-01 17:56:09 DEBUG    rasa_core.processor  - Predicted next action 'activate_restaurant' with prob 0.80.
2018-10-01 17:56:09 ERROR    rasa_core.processor  - Encountered an exception while running action 'activate_restaurant'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
2018-10-01 17:56:09 ERROR    rasa_core.processor  - The model predicted the custom action 'activate_restaurant' but you didn't configure an endpoint to run this custom action. Please take a look at the docs and set an endpoint configuration. https://rasa.com/docs/core/customactions/
Traceback (most recent call last):
  File "/home/sfrplindia1/Work/SantaFe/Raghuram/chatbots/venv3/lib/python3.5/site-packages/rasa_core/processor.py", line 324, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/sfrplindia1/Work/SantaFe/Raghuram/chatbots/venv3/lib/python3.5/site-packages/rasa_core/actions/action.py", line 305, in run
    "".format(self.name(), DOCS_BASE_URL))
Exception: The model predicted the custom action 'activate_restaurant' but you didn't configure an endpoint to run this custom action. Please take a look at the docs and set an endpoint configuration. https://rasa.com/docs/core/customactions/
2018-10-01 17:56:09 DEBUG    rasa_core.processor  - Action 'activate_restaurant' ended with events '[]'
2018-10-01 17:56:09 DEBUG    rasa_core.policies.memoization  - Current tracker state [{}, {'prev_action_listen': 1.0, 'intent_hi': 1.0}, {'prev_activate_restaurant': 1.0, 'intent_hi': 1.0}]
2018-10-01 17:56:09 DEBUG    rasa_core.policies.memoization  - There is no memorised next action
2018-10-01 17:56:09 DEBUG    rasa_core.featurizers  - Feature 'intent_hi' (value: '1.0') could not be found in feature map. Make sure you added all intents and entities to the domain
2018-10-01 17:56:09 DEBUG    rasa_core.featurizers  - Feature 'intent_hi' (value: '1.0') could not be found in feature map. Make sure you added all intents and entities to the domain
2018-10-01 17:56:09 DEBUG    rasa_core.policies.ensemble  - Predicted next action using policy_2_KerasPolicy
2018-10-01 17:56:09 DEBUG    rasa_core.processor  - Predicted next action 'deactivate_plan' with prob 0.66.
2018-10-01 17:56:09 ERROR    rasa_core.processor  - Encountered an exception while running action 'deactivate_plan'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
2018-10-01 17:56:09 ERROR    rasa_core.processor  - The model predicted the custom action 'deactivate_plan' but you didn't configure an endpoint t

**Comment by anishmahapatra** [comment]
Hi, you should add a file endpoints.yml with:

`action_endpoint:
  url: http://localhost:5005/webhook`

This should be put in the same folder where your Makefile is.
